//accts
export const GET_ACCTS_SUCCESS = 'GET_ACCTS_SUCCESS';
export const LOAD_PROJS_SUCCESS = 'LOAD_PROJS_SUCCESS';
export const GET_MAP_ACCTS_TO_PROJS_SUCCESS = 'GET_MAP_ACCTS_TO_PROJS_SUCCESS';
export const PROJ_RESOLVER_DEPLOYED_SUCCESS = 'PROJ_RESOLVER_DEPLOYED_SUCCESS';

export const PROJ_Created_FIRED = 'PROJ_Created_FIRED';