//accounts
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const LOAD_EVENTS_SUCCESS = "LOAD_EVENTS_SUCCESS";
export const GET_MAP_ACCOUNTS_TO_EVENTS_SUCCESS =
  "GET_MAP_ACCOUNTS_TO_EVENTS_SUCCESS";
export const EVENT_RESOLVER_DEPLOYED_SUCCESS =
  "EVENT_RESOLVER_DEPLOYED_SUCCESS";
